export const petsData = [
  {
    id: 1,
    name: "Jade",
    kind: "dog",
    weight: 2741,
    height: 20,
    length: 35,
    photo_url: "https://cdn2.thedogapi.com/images/rJH9KQoEX.gif",
    description: "Bacon ipsum dolor amet ham pork belly cupim rump salami",
  },
  {
    id: 2,
    name: "Stinky",
    kind: "cat",
    weight: 6712,
    height: 25,
    length: 52,
    photo_url: "https://cdn2.thecatapi.com/images/2lt.jpg",
    description:
      "I shall purr myself to sleep pee in the shoe scratch at fleas",
    number_of_lives: 5,
  },
  {
    id: 3,
    name: "Nitro",
    kind: "dog",
    weight: 7509,
    height: 60,
    length: 142,
    photo_url: "https://cdn2.thedogapi.com/images/BJT0Jx5Nm_1280.jpg",
    description: "Meatloaf sausage drumstick pork chop",
  },
  {
    id: 4,
    name: "Sabbath",
    kind: "cat",
    weight: 3490,
    height: 23,
    length: 45,
    photo_url: "https://cdn2.thecatapi.com/images/6tf.jpg",
    description: "Meow until belly rubs",
    number_of_lives: 6,
  },
  {
    id: 5,
    name: "Cutie",
    kind: "dog",
    weight: 1572,
    height: 20,
    length: 35,
    photo_url: "https://cdn2.thedogapi.com/images/HkuYlxqEQ_1280.jpg",
    description: "Long doggo heckin angery woofer snoot heckin angery woofer",
  },
  {
    id: 6,
    name: "Snap",
    kind: "cat",
    weight: 4623,
    height: 26,
    length: 50,
    photo_url: "https://cdn2.thecatapi.com/images/8k7.jpg",
    description:
      "I hide behind curtain when vacuum cleaner is on scratch strangers and poo on owners food but meow",
    number_of_lives: 7,
  },
  {
    id: 7,
    name: "Hennessy",
    kind: "dog",
    weight: 4193,
    height: 22,
    length: 59,
    photo_url: "https://cdn2.thedogapi.com/images/ry1kWe5VQ_1280.jpg",
    description:
      "Bacon ipsum dolor amet ham pork belly cupim rump salami, meatloaf sausage drumstick pork chop",
  },
  {
    id: 8,
    name: "Jasper",
    kind: "cat",
    weight: 2696,
    height: 23,
    length: 43,
    photo_url: "https://cdn2.thecatapi.com/images/aju.jpg",
    description: "Purr for no reason stand in doorway",
    number_of_lives: 4,
  },
  {
    id: 9,
    name: "Wizard",
    kind: "dog",
    weight: 2250,
    height: 45,
    length: 51,
    photo_url: "https://cdn2.thedogapi.com/images/SJp7Qe5EX_1280.jpg",
    description: "I am bekom fat super chub dat tungg tho",
  },
  {
    id: 10,
    name: "Oscar",
    kind: "cat",
    weight: 3612,
    height: 25,
    length: 49,
    photo_url: "https://cdn2.thecatapi.com/images/b93.png",
    description: "Meow meow mama bite off human's toes",
    number_of_lives: 1,
  },
];
